package newp;
import javax.swing.JOptionPane;
import java.awt.Toolkit;
import java.awt.*;
import java.awt.event.WindowEvent;
import newp.history;
import newp.LessonPage;
import newp.Messages;
import newp.Search;
import newp.TestPage;
import newp.history;
import newp.Test;
import newp.profile;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Onika11
 */


public class HomePage extends javax.swing.JPanel {
    
    

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        suggestButton = new javax.swing.JButton();
        SuggestTestButton = new javax.swing.JButton();
        SuggestLessonButton = new javax.swing.JButton();
        InboxButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollBar1 = new javax.swing.JScrollBar();
        ProfileButton = new javax.swing.JButton();
        QuizButton = new javax.swing.JButton();
        HistoryButton = new javax.swing.JButton();
        LessonButton = new javax.swing.JButton();
        SearchButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255), 5));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 600));

        suggestButton.setBackground(new java.awt.Color(204, 204, 204));
        suggestButton.setText("Suggested module:​  Module 12 ");

        SuggestTestButton.setText("Take test on Module 10");

        SuggestLessonButton.setText("Suggest module: Module 14");

        InboxButton.setText("Inbox");

        LogoutButton.setText("Logout");

        jLabel1.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 36)); // NOI18N
        jLabel1.setText("Feed");

        ProfileButton.setBackground(new java.awt.Color(51, 153, 255));
        ProfileButton.setText("Profile");

        QuizButton.setBackground(new java.awt.Color(51, 153, 255));
        QuizButton.setText("Quizzes");

        HistoryButton.setBackground(new java.awt.Color(51, 153, 255));
        HistoryButton.setText("History");

        LessonButton.setBackground(new java.awt.Color(102, 153, 255));
        LessonButton.setText("Lessons");

        SearchButton.setBackground(new java.awt.Color(102, 153, 255));
        SearchButton.setText("Search");
        SearchButton.setAutoscrolls(true);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Onika11\\Documents\\Capstone\\icon.jpg")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(517, 517, 517)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(QuizButton, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HistoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LessonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(ProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(211, 211, 211)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SuggestTestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SuggestLessonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(suggestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 245, Short.MAX_VALUE)
                        .addComponent(InboxButton)
                        .addGap(18, 18, 18)
                        .addComponent(LogoutButton)
                        .addGap(23, 23, 23))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InboxButton)
                            .addComponent(LogoutButton))
                        .addGap(147, 147, 147)
                        .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(ProfileButton)))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(suggestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(SuggestTestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(QuizButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(HistoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LessonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SuggestLessonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(35, 35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1088, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

       private void HistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {   
           
           history history = new history();
         history.setVisible(true);
       }
    
         private void LessonButtonActionPerformed(java.awt.event.ActionEvent evt) {    
             
             LessonPage lesson = new LessonPage();
         lesson.setVisible(true);
       }
    
        private void QuizButtonActionPerformed(java.awt.event.ActionEvent evt) { 
            
             TestPage test = new TestPage();
             test.setVisible(true);
            
       }
        
    
         private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) { 
             
              Search search = new Search();
         search.setVisible(true);
       }
    
         private void InboxButtonActionPerformed(java.awt.event.ActionEvent evt) {    
             Messages inbox = new Messages();
         inbox.setVisible(true);
       }
         
       private void SuggestLessonButtonActionPerformed(java.awt.event.ActionEvent evt) {    
           LessonPage lesson = new LessonPage();
           lesson.setVisible(true);
           
       }
          
       private void SuggestButtonActionPerformed(java.awt.event.ActionEvent evt) {   
            LessonPage lesson = new LessonPage();
           lesson.setVisible(true);
           
       }
         private void SuggestTestButtonActionPerformed(java.awt.event.ActionEvent evt) {   
              Test test = new Test();
           test.setVisible(true);
           
       }
             private void profileButtonActionPerformed(java.awt.event.ActionEvent evt) {   
             profile profile = new profile();
            profile.setVisible(true);
           
       }
    
          public static void main (String [] args){
            java.awt.EventQueue.invokeLater(new Runnable(){
                public void run(){
                    new HomePage().setVisible(true);
                }
            });
        }
    
    
          
             
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HistoryButton;
    private javax.swing.JButton InboxButton;
    private javax.swing.JButton LessonButton;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton ProfileButton;
    private javax.swing.JButton QuizButton;
    private javax.swing.JButton SearchButton;
    private javax.swing.JButton SuggestLessonButton;
    private javax.swing.JButton SuggestTestButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JButton suggestButton;
    // End of variables declaration//GEN-END:variables
}
